name: python_tools_env
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - anyio
  - appdirs
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - astunparse
  - attrs
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - bokeh
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - contourpy
  - cryptography
  - cycler
  - daal4py
  - dal
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - execnb
  - executing
  - expat
  - fastcore
  - fontconfig
  - fonttools
  - freetype
  - ghapi
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - iniconfig
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab_pygments
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libllvm10
  - libpng
  - libpq
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpi
  - mpich
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbdev
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pluggy
  - ply
  - pooch
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pyrsistent
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - qt-webengine
  - qtwebkit
  - readline
  - requests
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - tbb
  - terminado
  - testbook
  - threadpoolctl
  - tikzmagic
  - tinycss2
  - tk
  - toml
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - watchdog
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xyzservices
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
